### ISSUE TITLE
Incorrectly enforcing a limit? Blackjack can't mount AC/2

### ISSUE THREAD

**Issue by Beetlecat** [CptMoore/HardpointFixMod#1] opened 2018-05-17 23:16 UTC
Trying a quick run with this mod via the Mod Tools install, and attempting to fix a blown-off arm results in not being able to mount an AC/2, even though the limb shows a 0/1 ballistic slot available.

Setting "enforceHardpointLimits" to false allowed me to install the AC/2.

**Comment by CptMoore** [comment] 2018-05-18 01:15
unfortunately, some mechs don't have enough actual hardpoint models added to the game. my mod enforces the limit to only mount weapons that then can be visually seen on a mech.

in addition, I didn't change any existing mechs default loadouts, so mechs can loose weapons they can never put back again. its not really nice that way thought.

I should probably add exceptions to weapons that are mounted in default loadouts and just add a warning when dropping such weapons back into a mech. Of course that should be able to be toggled on and off in the settings.

Btw, the blackjack really cant mount AC2... AC20, AC10 and AC5 are fine though ....  (each [] group represents a hardpoint that supports the list of weapons basically)

Excerpt from hardpointdatadef_blackjack.json:
```
        {
            "location" : "leftarm",
            "weapons" : [
                [
                    "chrPrfWeap_blackjack_leftarm_ac10_bh1",
                    "chrPrfWeap_blackjack_leftarm_ac20_bh1",
                    "chrPrfWeap_blackjack_leftarm_ac5_bh1",
                    "chrPrfWeap_blackjack_leftarm_flamer_eh1",
                    "chrPrfWeap_blackjack_leftarm_gauss_eh1",
                    "chrPrfWeap_blackjack_leftarm_laser_eh1",
                    "chrPrfWeap_blackjack_leftarm_lbx_bh1",
                    "chrPrfWeap_blackjack_leftarm_mg_bh1",
                    "chrPrfWeap_blackjack_leftarm_ppc_eh1",
                    "chrPrfWeap_blackjack_leftarm_uac5_bh1"
                ],
                [
                    "chrPrfWeap_blackjack_leftarm_ac5_bh2",
                    "chrPrfWeap_blackjack_leftarm_flamer_eh2",
                    "chrPrfWeap_blackjack_leftarm_laser_eh2",
                    "chrPrfWeap_blackjack_leftarm_mg_bh2",
                    "chrPrfWeap_blackjack_leftarm_ppc_eh2",
                    "chrPrfWeap_blackjack_leftarm_uac5_bh2"
                ],
                [
                    "chrPrfWeap_blackjack_leftarm_ac5_bh3",
                    "chrPrfWeap_blackjack_leftarm_flamer_eh3",
                    "chrPrfWeap_blackjack_leftarm_laser_eh3",
                    "chrPrfWeap_blackjack_leftarm_mg_bh3",
                    "chrPrfWeap_blackjack_leftarm_ppc_eh3",
                    "chrPrfWeap_blackjack_leftarm_uac5_bh3"
                ]
            ],
            "blanks" : [
                
            ],
            "mountingPoints" : [
                
            ]
        }
```

**Comment by Beetlecat** [comment] 2018-05-18 02:08
Oh! That's really curious about the blackjack. Obviously an odd duck, since it's the starting mech.

Wait-- is that right? I just looked it up in-game and on sarna. The BJ-1 default loadout is 2xAC/2s. AC/20s on that mech would be amazing! 😄

**Comment by CptMoore** [comment] 2018-05-18 07:35
> So, in this case, it's a "bug" of sorts due to HBS not having AC/2 models for that spot?

yea. maybe they figured AC5 models looks good enough and they don't need to import the AC2 models.

In the tabletop game, as I understood it, you can mount everywhere anything as much as tonnage and slots allow it.

So this mod is by definition not Cannon, as it limits hardpoint placement. I just pretend not all spare parts for all mechs are available and therefore some weapons can't be mounted. Works even for the stock loadout issues, those are factory made mechs, and the argo just cant reassembly those mounts (must be the bad quality of the cyborg arm of the engineer).

In any case I think I'll add the option to either detect loadout issues, or make the error just a warning if enforceHardpointLimits == false

**Comment by Beetlecat** [comment] 2018-05-18 22:13
Hmm -- I like that justification too, though it's fraught with frustration once you start replacing mech parts in-game and can't rebuild things they way they were. A real sense of attrition of technology... Those custom factory mounts aren't easily fabricated -- though that's why we carry around a whole ship-worth of mech scrap. ;)

Another "victim" of this is the head-mounted ML in the Vindicator VND-1R. It looks like *A* laser is modeled, but not the usual ML one?

What effect does adding an entry for the desired weapon to the hardpointdatadef_* have?

**Comment by CptMoore** [comment] 2018-05-19 12:31
>What effect does adding an entry for the desired weapon to the hardpointdatadef_* have?

good questions about adding nonexisting hardpoint data, but those things are in the end actual assets that have to be loaded, I would guess infinite loading spinner if assets can't be loaded.

> (no L/M/S?)

yep, your LL looks the same as a SL. At least PPCs look different!

> Setting enforcehardpointlimits=true wouldn't allow me to mount a ML+ to swap out the stock ML.

are you using a mod that adds a weapon with a PrefabIdentifier that does not say "Laser" ?

Weapon_Laser_SmallLaser_1-ExoStar.json
```
 "PrefabIdentifier" : "Laser",
```

That mod should fix that or those weapons will only show up on a mech as the first hardpoint entry of a location (in this case a flamer).

Otherwise add the weapons JSON here to the issue, I'll take a look at it.

**Comment by Beetlecat** [comment] 2018-05-19 19:49
Cool! Thank you. 

But to answer your previous question -- no, I had no weapon-changing mods active. Just was wanting to upgrade the vindicator's head laser from M to M+.

**Comment by CptMoore** [comment] 2018-05-19 22:02
I wasn't able to reproduce your problem. Can you add a new entry to HardpointFixMod/Settings.json
```
"logLevel": "Debug"
```
don't forget to add any necessary commas

then try it out again and then attach HardpointFixMod/log.txt to this issue?

**Comment by thrandisher** [comment] 2018-05-19 23:41
Just wanted to say i encountered the same problem.

Now im using the last push you did a few hours ago with the new option for default weapons and it seems to work to replace a "stock" mech, well except if i try to mount a + weapon on that blackjack slot, then i get the hardpoint mount error.

I am heavly modified tho

**Comment by CptMoore** [comment] 2018-05-20 08:06
do you guys try to replace the laser by dragging it ontop of an existing laser? remove the existing laser before dragging the new one in, there is a relative large if from the original code I did not want copy, and thats about allowing replacement of weapons.

**Comment by Beetlecat** [comment] 2018-05-20 20:39
> do you guys try to replace the laser by dragging it ontop of an existing laser? remove the existing laser before dragging the new one in (all without closing the mechbar or saving the mech), there is a relative large if from the original code I did not want copy, and thats about allowing replacement of weapons.

That method seems to work. I can re-trigger the error by putting a normal ML in the slot, then trying to drop-swap with a + version. Pulling it out first, then installing the new weapon worked.

**Comment by CptMoore** [comment] 2018-05-20 21:34
> That method seems to work. I can re-trigger the error by putting a normal ML in the slot, then trying to drop-swap with a + version. Pulling it out first, then installing the new weapon worked.

Ok I'll try to get the replacement logic to work

> dragged the ac/2 off, then dragged a ac/2+ 

oh yea my patch requires the exact same component for replacement, I'll see if I can detect straight + upgrades easily

**Comment by CptMoore** [comment] 2018-05-20 21:35
btw thanks for reporting and testing, here a small sneak peek for an upcoming mod

![sneak_peek](https://user-images.githubusercontent.com/39010654/40283908-804a7854-5c86-11e8-9522-ca4e79fc1da9.png)
![geek_out_please](https://user-images.githubusercontent.com/39010654/40283909-839c3470-5c86-11e8-9782-ce927b3ca990.png)

**Comment by CptMoore** [comment] 2018-05-20 21:50
> dragged the ac/2 off, then dragged a ac/2+

should be fixed in the latest download

**Comment by CptMoore** [comment] 2018-05-20 21:52
>> That method seems to work. I can re-trigger the error by putting a normal ML in the slot, then trying to drop-swap with a + version. Pulling it out first, then installing the new weapon worked.

> Ok I'll try to get the replacement logic to work

I lied, looks too complicated to maintain (in relation to the gain), I'll add this to a limitation section in the readme sry

**Comment by thrandisher** [comment] 2018-05-21 01:17
Thats a bummer. As i think of it, i never did a recompile of the dll, just droped the other files into it. Been years since ive done that, lol.

Looking at the examples above and how there are a few mechs that have this problem, could those mechs be overwriten for hardpoints with a modtek mod? I do have some questions about it but ill ask over on reddit when i have time.

**Comment by thrandisher** [comment] 2018-05-21 18:08
It doesn't look like im going to have time again today as ill probably be in and out of hospital/er again.  At least for me, things seemed to be working last night when i tried.  If I have time later ill try checking a few of those other mechs i saw problems with on Reddit and see if it persist for me or not, with this latest version.

**Comment by CptMoore** [comment] 2018-05-21 23:32
@thrandisher  sorry to hear that. I always appreciate people testing mods!

**Comment by thrandisher** [comment] 2018-05-22 21:48
Wanted to chip in real fast before you closed this. 

I think i ran into another small bug related to this, but I won't have time to fully test until late tonight (patch, and fixing stuff due to patch took way to much time)

mostly involves replacing a broken weapon with a moded weapon of the same time. example, lrm with a incenerary lrm.

Ill test tonight when i do have time and eather edit this post or a new one.

Heck, it might not even be related to this and i could have tunnel vision/witch hunt mode one since its a hardpoint issue, lol. Anyway, ill post results and how to reproduce it and all that jazz later.

**Comment by CptMoore** [comment] 2018-05-23 10:46
thanks for testing, if there are still issues, even if only QoL, just continue to report them

**Closed by CptMoore** 2018-05-23 10:46 UTC
